### ISSUE TITLE
Merge as module with main SDK

### ISSUE THREAD

**Issue by mtrezza** [parse-community/ParseLiveQuery-iOS-OSX#262]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/ParseLiveQuery-iOS-OSX/issues?q=is%3Aissue).

### Current Limitation

This repo needs to be maintained separately from the main SDK.

### Feature / Enhancement Description

Now that the main Parse iOS SDK supports SPM, this LiveQuery repository can be merged with it and added as a module. The module can be optionally installed when adding the SDK via SPM.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by proj-sashido** [comment]
is there a timeframe on this? this is the only thing stopping me from using SPM/Parse in our projects because ParseLiveQuery relies on Parse being installed via Cocoapods

**Comment by mtrezza** [comment]
We don't have a timeframe for that yet. Did you try to add the main Parse SDK via SPM and add the LiveQuery SDK via Cocoapods until then?

**Comment by proj-sashido** [comment]
My use case is I have a local framework that uses ParseCore as a dependency (via SPM), and when I try to add the LiveQuery SDK via Cocoapods, it throws up a bunch of errors. 

One such error:
`Include of non-modular header inside framework module 'Parse.PFAnalytics': '/Users/name/Library/Developer/Xcode/DerivedData/AppName-dvagborctkocfhgsmprcwdkloacd/Build/Products/Debug-appletvsimulator/Bolts/Bolts.framework/Headers/BFTask.h'`

Admittedly, I haven't spent a lot of time debugging it or trying to get it work; my guess was simply that it didn't like the conflict between the Parse SDK that is brought it via LiveQuery SDK's dependency in cocoapods, and the ParseCore SDK from SPM

I've just taken out the ParseCore dependency from my local framework for the time being, and am going with Cocoapods

**Comment by mtrezza** [comment]
Got it, I'm confident we'll get this module merged with the main SDK in the coming weeks.

**Comment by sidan5** [comment]
@mtrezza Any timeframe? would it happen? Thanks!

**Comment by mtrezza** [comment]
You can follow the effort here:

https://github.com/parse-community/Parse-SDK-iOS-OSX/pull/1712

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1714
